
services:
  api-gym-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgre
      - POSTGRESQL_PASSWORD=postgre
      - POSTGRESQL_DATABASE=api_gyms